
runtime: nodejs16
entrypoint: npm start
instance_class: F2
env_variables:
  GCLOUD_STORAGE_BUCKET: "strengthtest-353601.appspot.com"
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
